### ISSUE TITLE
Non-existing export is imported

### ISSUE THREAD

**Issue by WardBrink** [concurrent-tasks/concurrent-tasks#28]
Hi guys,

When trying to use this module with the follow code, I get the following error:

**Code:**
`import TaskRunner from "concurrent-tasks";
const runner = new TaskRunner();`

**Error:**
`node_modules\concurrent-tasks\es\index.js (11:74) Error: Non-existent export 'setAppropriateConcurrency' is imported from node_modules\concurrent-tasks\es\PrivateFunctions.js 9: function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
10: 
11: import { startCheckAndRun, runPending, startCheck, addCheck, removeCheck, setAppropriateConcurrency } from './PrivateFunctions';
                                                                              ^
12: import log from './log';`

Can anyone help with this?

**Comment by samrith-s** [comment]
Hello @WardBrink,

Thanks for the report and sorry for the extreme delay in responding. 

Can you try out the v2 version? It has a better API and more extensibility as well as being the version that's going to replace this package in the future. 

Let me know if you still have this issue with it.
